// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID     *string `json:"id,omitempty"`
	Post   *Post   `json:"post,omitempty"`
	Author *User   `json:"author,omitempty"`
	Body   *string `json:"body,omitempty"`
}

func (Comment) IsEntity() {}

type Post struct {
	ID      *string    `json:"id,omitempty"`
	Title   *string    `json:"title,omitempty"`
	Body    *string    `json:"body,omitempty"`
	Author  *User      `json:"author,omitempty"`
	Comment []*Comment `json:"comment"`
}

func (Post) IsEntity() {}

type Query struct {
}

type User struct {
	ID *string `json:"id,omitempty"`
}

func (User) IsEntity() {}
