name: Update go.mod

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜日の00:00 UTCに実行

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Get current date
        id: date
        run: echo "date=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Update go.mod
        run: |
          rm -f go.mod go.sum
          go mod init github.com/yujiorama/graphql-schema-subgraph-migrator
          go get github.com/99designs/gqlgen@latest
          go mod tidy

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            Update go.mod and go.sum

            Created by ${{ github.actor }} at ${{ steps.date.outputs.date }}

            - Update Go dependencies to latest versions
            - Run go mod tidy
          branch: update-go-mod
          delete-branch: true
          title: 'build: update Go dependencies'
          body: |
            This PR updates the Go dependencies to their latest versions.

            Created by GitHub Actions at ${{ steps.date.outputs.date }} UTC.

            <details>
            <summary>Changes in go.mod</summary>

            ```diff
            $(git diff --no-color go.mod || echo "No changes in go.mod")
            ```
            </details>

            <details>
            <summary>Changes in go.sum</summary>

            ```diff
            $(git diff --no-color go.sum || echo "No changes in go.sum")
            ```
            </details>
          labels: |
            dependencies
            automated-pr
