name: Update go.sum

on:
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Update go.sum
        run: |
          go mod tidy

      - name: Check for changes
        id: git-check
        run: |
          git add go.sum
          if ! git diff --cached --quiet; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate_token.outputs.token }}
          commit-message: |
            Update go.sum

            Created by ${{ github.actor }} at ${{ steps.date.outputs.date }}

            - Update Go dependencies to latest versions
            - Run go mod tidy
          branch: update-go-sum
          delete-branch: true
          title: 'build: update Go dependencies'
          body: |
            This PR updates the Go dependencies to their latest versions.

            Created by GitHub Actions at ${{ steps.date.outputs.date }} UTC.

            <details>
            <summary>Changes in go.sum</summary>

            ```diff
            $(git diff --no-color go.sum || echo "No changes in go.sum")
            ```
            </details>
          labels: |
            dependencies
            automated-pr
